config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "beans_comments#index"
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
  resources :users
  put "users/:id/hide", to: "users#hide", as: "users_hide"
  get "users/:id/profile", to: "users#show", as: "user_profile"
  resources :shops do
    resources :shop_comments
  end
  resources :beans do
    resources :beans_comments
  end
  resources :users, only: [:show, :edit]

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    get "users/sign_out" => "devise/sessions#destroy"
  end
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user
  has_many :beans, dependent: :destroy
  has_many :shop_comments, dependent: :destroy

  validates :name, presence: true
  validates :prefecture, exclusion: { in: %w[---], message: "を選択してください" }
  validates :address, presence: true

  DEFAULTLATE = 0.0

  enum prefecture: {
    北海道: 1, 青森県: 2, 岩手県: 3, 宮城県: 4, 秋田県: 5, 山形県: 6, 福島県: 7,
    茨城県: 8, 栃木県: 9, 群馬県: 10, 埼玉県: 11, 千葉県: 12, 東京都: 13, 神奈川県: 14,
    新潟県: 15, 富山県: 16, 石川県: 17, 福井県: 18, 山梨県: 19, 長野県: 20,
    岐阜県: 21, 静岡県: 22, 愛知県: 23, 三重県: 24,
    滋賀県: 25, 京都府: 26, 大阪府: 27, 兵庫県: 28, 奈良県: 29, 和歌山県: 30,
    鳥取県: 31, 島根県: 32, 岡山県: 33, 広島県: 34, 山口県: 35,
    徳島県: 36, 香川県: 37, 愛媛県: 38, 高知県: 39,
    福岡県: 40, 佐賀県: 41, 長崎県: 42, 熊本県: 43, 大分県: 44, 宮崎県: 45, 鹿児島県: 46,
    沖縄県: 47
  }

  def update_rate_average
    if shop_comments.present?
      shop_comments_average = shop_comments.average(:rate)
      update(rate_average: shop_comments_average)
    else
      update(rate_average: DEFAULTLATE)
    end
  end

  mount_uploader :img, ImgUploader
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!, { except: [:index] }
  before_action :set_shop, { only: [:show, :edit, :update, :destroy] }
  before_action :set_shop_q, { only: [:index] }

  PER_PAGE = 9

  def index
    if params[:q].present?
      @shops = @q.result.page(params[:page]).per(PER_PAGE)
      @count = @shops.total_count
    else
      params[:q] = { sorts: "created_at desc" }
      @shops = Shop.order(:created_at).page(params[:page]).per(PER_PAGE)
    end
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = current_user.shops.new(shop_params)
    if @shop.save
      redirect_to shops_path, notice: "登録しました"
    else
      flash.now[:alert] = "登録に失敗しました"
      render :new
    end
  end

  def show
    @beans = Bean.where(shop_id: @shop.id)
    @shop_comments = @shop.shop_comments
    @shop_comment = current_user.shop_comments.new
    @average_rate = if @shop.shop_comments.blank?
                      0
                    else
                      @shop.shop_comments.average(:rate).round(2)
                    end
  end

  def edit; end

  def update
    @shop.update!(shop_params)
    redirect_to @shop, notice: "店舗情報を更新しました"
  end

  def destroy
    @shop.destroy!
    redirect_back(fallback_location: root_path, notice: "削除しました")
  end

  private

  def set_shop
    @shop = Shop.find(params[:id])
  end

  def shop_params
    params.require(:shop).permit(:name, :prefecture, :address, :TEL, :URL, :img, :user_id)
  end

  def set_shop_q
    @q = Shop.ransack(params[:q])
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_shop-bean.html.erb
<div class="bean-name">
  <li>
    <a class="steel-gray" href="/beans/<%= bean.id %>"><%= bean.name %></a>
  </li>
</div>

app/views/shops/_shop-comments.html.erb
  
<div class="comments">
  <div class="row">
    <div class="col-2 registered-user">
      <a class="steel-gray" href="/users/<%= c.user.id %>"><img src=<%= c.user.img.url %> class="icon-image-mini">
        <p><%= c.user.name %></p>
      </a>
    </div>
    <div class="col-10 comment">
      <p><%= c.content %></p>
      <hr>
      <div class="rate-star">
        <div class="row">
          <div class="col-5 rate">
            <p>評価：<%= c.rate %>点</p>
          </div>
          <div class="col-7 star-rate">
            <div id="star-rate<%= c.id %>"></div>
            <script>
              $('#star-rate<%= c.id%>').empty();
                $('#star-rate<%= c.id%>').raty({
                  size      : 36,
                  starOff   : '<%= asset_path('star-off.png') %>',
                  starOn    : '<%= asset_path('star-on.png') %>',
                  half      : false,
                  readOnly: true,
                  score: <%= c.rate %>,
                });
            </script>
          </div>
        </div>
      </div>
      <div class="row delete-link">
        <% if current_user && current_user.id == c.user_id %>
          <%= link_to "削除", shop_shop_comment_path(@shop, c), method: :delete, data: { confirm: "削除しますか？" } %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shops/_shop-form.html.erb
<div class="form-wrapper">
  <%= form_with model: @shop, local: true do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <div class=form-group>
      <span class="essential">※</span><%= f.label :name, "店舗名" %>
      <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: "最大50文字", maxlength: 50 %>
    </div>
    <div class=form-group>
      <span class="essential">※</span><%= f.label :prefecture, "都道府県" %>
      <%= f.select :prefecture, Shop.prefectures.keys.map {|k| [k, k]}, {}, {class: "form-control", style: "margin-bottom: 15px;", data: {} } %>
    </div>
    <div class=form-group>
      <span class="essential">※</span><%= f.label :address, "住所" %>
      <%= f.text_field :address, autofocus: true, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :TEL, "電話番号" %>
      <%= f.text_field :TEL, autofocus: true, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :URL, "URL" %>
      <%= f.url_field :URL, autofocus: true, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :img, "店舗画像" %><br />
      <%= f.file_field :img %>
    </div>
    <div class="search-button">
      <%= f.submit "登録", class: "btn btn-block form-submit-btn" %>
    </div>
  <% end %>
</div>

app/views/shops/_shop.html.erb
<div class="cards">
  <a href="/shops/<%= shop.id %>" class="cards-body">
    <div class="cards-header">
      <% if shop.img? %>
        <img src=<%= shop.img.url %>>
      <% else %>
        <%= image_tag "default-shops.jpg" %>
      <% end %>
    </div>
    <div class="bean-title">
      <P class="name"><%= shop.name %></P>
    </div>
  </a>
  <div class="contents steel-gray">
    <div class="shop-address">
      <p><%= shop.prefecture %><%= shop.address %></p>
    </div>
    <div class="shop-rate">
      <div class="average-review-rating" data-score=<%= shop.rate_average %>></div>
      <script>
        $('.average-review-rating').empty();
          $('.average-review-rating').raty({
            readOnly: true,
            starOn: "<%= asset_path('star-on.png') %>",
            starOff: "<%= asset_path('star-off.png') %>",
            starHalf: "<%= asset_path('star-half.png') %>",
            score: function() {
              return $(this).attr('data-score')
            }
          });
      </script>
    </div>
  </div>
  <p class="link-box">
    <% if user_signed_in? && current_user.id == (shop.user_id).to_i %>
      <%= link_to "編集", edit_shop_path(shop) %>
      <%= link_to "削除", shop_path(shop), method: :delete, data: { confirm: "削除しますか？" } %>
    <% end %>
  </p>
</div>

app/views/shops/_shop_form.html.erb
<div class="form-wrapper">
  <%= form_with model: @shop, local: true do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <div class=form-group>
      <span class="essential">※</span><%= f.label :name, "店舗名" %>
      <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: "最大50文字", maxlength: 50 %>
    </div>
    <div class=form-group>
      <span class="essential">※</span><%= f.label :prefecture, "都道府県" %>
      <%= f.select :prefecture, Shop.prefectures.keys.map {|k| [k, k]}, {}, {class: "form-control", style: "margin-bottom: 15px;", data: {} } %>
    </div>
    <div class=form-group>
      <span class="essential">※</span><%= f.label :address, "住所" %>
      <%= f.text_field :address, autofocus: true, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :TEL, "電話番号" %>
      <%= f.text_field :TEL, autofocus: true, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :URL, "URL" %>
      <%= f.url_field :URL, autofocus: true, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :img, "店舗画像" %><br />
      <%= f.file_field :img %>
    </div>
    <div class="search-button">
      <%= f.submit "登録", class: "btn btn-block form-submit-btn" %>
    </div>
  <% end %>
</div>

app/views/shops/edit.html.erb
<div class="container">
  <h1 class="title mt-3">お店を編集</h1>
  <%= render "shop-form" %>
</div>

app/views/shops/index.html.erb
<div class="row">
  <div class="col-xl-3 search-form">
    <div class="form-wrapper">
      <h1 class="title">Search</h1>
      <%= search_form_for @q, url: shops_path do |f| %>
        <div class="form-group">
          <%= f.label "並べ替え", {class: "search-tag"} %>
          <%= f.select( :sorts, {"新着順": "created_at desc", "評価が高い順": "rate_average desc"}, { selected: params[:q][:sorts] }, class: "form-control") %>
        </div>
        <div class=form-group>
          <%= f.label :name_cont, "店舗名", {class: "search-tag"} %>
          <%= f.search_field :name_cont, autofocus: true, class: "form-control" %>
        </div>
        <div class=form-group>
          <%= f.label :prefecture_eq, "都道府県", {class: "search-tag"} %>
          <%= f.select :prefecture_eq, Shop.prefectures_i18n.invert.map { |key, value| [key, Shop.prefectures[value]]}, {include_blank: "指定なし"}, { class: "form-control", style: "margin-bottom: 15px;", data: {} } %>
        </div>
        <div class=form-group>
          <%= f.label :address_cont, "住所", {class: "search-tag"} %>
          <%= f.search_field :address_cont, autofocus: true, class: "form-control" %>
        </div>
        <div class="search-button">
          <%= f.submit "検索", class: "btn  btn-block form-submit-btn" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-xl-9 shops">
    <h1 class="title">Shops</h1>
    <h4 class="title text-center mb-5"><%= @count %>件の検索結果</h4>
    <div class="wrap">
      <%= render @shops %>
    </div>
  </div>
</div>
<%= paginate @shops %>

app/views/shops/new.html.erb
<div class="container">
  <h1 class="title mt-3">お店を登録</h1>
  <%= render "shop-form" %>
</div>

app/views/shops/show.html.erb
<h1 class="title mt-3"><%= @shop.name %></h1>
<div class="shop-show">
  <div class=row>
    <%= render partial: "layouts/object-img", locals: { object: @shop, img: "shops" } %>
    <div class="col-xl-8 shop-detail">
      <div class="row">
        <div class="col-lg-6 shop-about">
          <h2 class="title show">About</h2>
          <table class="table table-borderless">
            <tbody>
              <tr>
                <th scope="row">平均評価</th>
                <td>
                  <div class="average-review-rating" data-score=<%= @shop_comments.average(:rate) %>></div>
                  <%= render "/layouts/average" %>
                </td>
                <td>
                  <span class="small"><%= @shop.shop_comments.count %> 件の評価</span>
                </td>
              </tr>
              <tr>
                <th scope="row">住所</th>
                <td colspan="2"><%= @shop.prefecture %><%= @shop.address %></td>
              </tr>
              <tr>
                <th scope="row">電話番号</th>
                <td colspan="2">
                  <% if @shop.TEL? %>
                    <div class="shop-TEL"><%= @shop.TEL %></div>
                  <% end%>
                </td>
              </tr>
              <tr>
                <th scope="row">URL</th>
                <td colspan="2">
                  <% if @shop.URL? %>
                    <div class="steel-gray"><%= text_url_to_link(h(@shop.URL)).html_safe %></div>
                  <% end%>
                </td>
              </tr>
              <tr>
                <th scope="row">取扱豆</th>
                <td colspan="2 bean-name">
                  <%= render partial: "shop-bean", collection: @beans, as: :bean %>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="col-lg-6 shop-comments">
          <h2 class="title show">Comments</h2>
          <%= render partial: "shop-comments", collection: @shop_comments, as: :c %>
          <div class="comments">
            <%= form_with(model: [@shop, @shop_comment]) do |f| %>
              <table class="table table-borderless">
                <tbody>
                  <tr>
                    <th scope="row">内容</th>
                    <td colspan="2"><%= f.text_area :content %></td>
                  </tr>
                  <tr>
                    <th scope="row">評価</th>
                    <td>
                      <div class="form-group comment-rate" id="star">
                        <%= f.hidden_field :rate, id: :review_star %>
                      </div>
                      <%= f.hidden_field :shop_id, value: @shop.id %>
                      <br>
                    </td>
                  </tr>
                  <tr>
                    <td colspan="2">
                      <div class="comment-button">
                        <%= f.submit "コメントする", class: "btn  btn-block form-submit-btn" %>
                      </div>
                    </td>
                  </tr>
                </tbody>
              </table>
              <script>
                $('#star').empty();
                  $('#star').raty({
                    size     : 36,
                    starOff:  '<%= asset_path('star-off.png') %>',
                    starOn : '<%= asset_path('star-on.png') %>',
                
                    scoreName: 'shop_comment[rate]',
                    half: false,
                  });
              </script>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>