config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "beans_comments#index"
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
  resources :users
  put "users/:id/hide", to: "users#hide", as: "users_hide"
  get "users/:id/profile", to: "users#show", as: "user_profile"
  resources :shops do
    resources :shop_comments
  end
  resources :beans do
    resources :beans_comments
  end
  resources :users, only: [:show, :edit]

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    get "users/sign_out" => "devise/sessions#destroy"
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :shops, dependent: :destroy
  has_many :beans, dependent: :destroy
  has_many :shop_comments, dependent: :destroy
  has_many :beans_comments, dependent: :destroy

  validates :name, presence: true, length: { maximum: 30 }
  validates :self_introduction, length: { maximum: 500 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :img, ImgUploader

  def self.guest
    find_or_create_by!(email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

module Users
  class ConfirmationsController < Devise::ConfirmationsController
    # GET /resource/confirmation/new
    # def new
    #   super
    # end

    # POST /resource/confirmation
    # def create
    #   super
    # end

    # GET /resource/confirmation?confirmation_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after resending confirmation instructions.
    # def after_resending_confirmation_instructions_path_for(resource_name)
    #   super(resource_name)
    # end

    # The path used after confirmation.
    # def after_confirmation_path_for(resource_name, resource)
    #   super(resource_name, resource)
    # end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    # You should configure your model like this:
    # devise :omniauthable, omniauth_providers: [:twitter]

    # You should also create an action method in this controller like this:
    # def twitter
    # end

    # More info at:
    # https://github.com/heartcombo/devise#omniauth

    # GET|POST /resource/auth/twitter
    # def passthru
    #   super
    # end

    # GET|POST /users/auth/twitter/callback
    # def failure
    #   super
    # end

    # protected

    # The path used when OmniAuth fails
    # def after_omniauth_failure_path_for(scope)
    #   super(scope)
    # end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

module Users
  class PasswordsController < Devise::PasswordsController
    # GET /resource/password/new
    # def new
    #   super
    # end

    # POST /resource/password
    # def create
    #   super
    # end

    # GET /resource/password/edit?reset_password_token=abcdef
    # def edit
    #   super
    # end

    # PUT /resource/password
    # def update
    #   super
    # end

    # protected

    # def after_resetting_password_path_for(resource)
    #   super(resource)
    # end

    # The path used after sending reset password instructions
    # def after_sending_reset_password_instructions_path_for(resource_name)
    #   super(resource_name)
    # end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    before_action :ensure_normal_user, only: %i[update destroy]
    # before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # def update; end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_up_params
    #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
    # end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end

    protected

    def after_update_path_for(_resource)
      user_path(id: current_user.id)
    end

    def ensure_normal_user
      redirect_to root_path, alert: "ゲストユーザーの更新・削除はできません" if resource.email == "guest@example.com"
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
    before_action :reject_user, only: [:create]
    # before_action :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    # def new
    #   super
    # end

    # POST /resource/sign_in
    # def create
    #   super
    # end

    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    # end
    def guest_sign_in
      sign_in User.guest
      redirect_to beans_path, notice: "ゲストユーザーとしてログインしました。"
    end

    protected

    def reject_user
      @user = User.find_by(email: params[:user][:email].downcase)
      if @user
        if @user.valid_password?(params[:user][:password]) && (@user.active_for_authentication? == false)
          flash[:alert] = "退会済みです。"
          redirect_to new_user_session_path
        end
      else
        flash[:alert] = "必須項目を入力してください。"
      end
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

module Users
  class UnlocksController < Devise::UnlocksController
    # GET /resource/unlock/new
    # def new
    #   super
    # end

    # POST /resource/unlock
    # def create
    #   super
    # end

    # GET /resource/unlock?unlock_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after sending unlock password instructions
    # def after_sending_unlock_instructions_path_for(resource)
    #   super(resource)
    # end

    # The path used after unlocking the resource
    # def after_unlock_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, { only: [:show, :hide] }
  def show
    @shops = Shop.where(user_id: @user.id)
    @beans = Bean.where(user_id: @user.id)
  end

  def hide
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "ご利用いただきありがとうございました。"
    redirect_to root_path
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user-bean.html.erb
<div class="card mb-4 rounded">
  <div class="card-body bg-lemon">
    <h6 class="card-title"><a href="/beans/<%= bean.id %>"><%= bean.name %></a></h6>
    <table class="table">
      <tbody>
        <tr>
          <th scope="row">価格</th>
          <td><%= bean.price %><span>円</span></td>
        </tr>
        <tr>
          <th scope="row">投稿日</th>
          <td><%= bean.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
      </tbody>
    </table>
    <p class="link-box">
      <% if user_signed_in? && current_user.id == bean.user_id %>
        <%= link_to "編集", edit_bean_path(bean) %>
        <%= link_to "削除", bean_path(bean), method: :delete, data: { confirm: "削除しますか？" } %>
      <% end %>
    </p>
  </div>
</div>

app/views/users/_user-shop.html.erb
<div class="card mb-4 rounded">
  <div class="card-body bg-lemon">
    <h6 class="card-title"><a href="/shops/<%= shop.id %>"><%= shop.name %></a></h6>
    <table class="table">
      <tbody>
        <tr>
          <th scope="row">住所</th>
          <td><%= shop.prefecture %><%= shop.address %></td>
        </tr>
        <tr>
          <th scope="row">投稿日</th>
          <td><%= shop.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
      </tbody>
    </table>
    <p class="link-box">
      <% if user_signed_in? && current_user.id == (shop.user_id).to_i %>
        <%= link_to "編集", edit_shop_path(shop) %>
        <%= link_to "削除", shop_path(shop), method: :delete, data: { confirm: "削除しますか？" } %>
      <% end %>
    </p>
  </div>
</div>

app/views/users/show.html.erb
<div class="profile-wrap">
  <div class="row">
    <div class="col-md-6 text-center">
      <img src=<%= @user.img.url %> class="icon-image">
    </div>
    <div class="col-md-6 text-center">
      <h1 class="title"><%= @user.name %></h1>
      <% if @user.self_introduction.present? %>
        <h6 class="introduction steel-gray bg-lemon"><%= @user.self_introduction %></h6>
      <% else %>
        <h6 class="introduction steel-gray bg-lemon"><%= @user.name %>です</h6>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <h1 class="title mt-5">登録した焙煎店</h1>
      <hr class="style-1">
      <% if @shops.present? %>
        <%= render partial: "user-shop", collection: @shops, as: :shop %>
      <% else %>
        <h3 class="text-center steel-gray">まだ登録がありません</h3>
      <% end %>
    </div>
    <div class="col-md-6">
      <h1 class="title mt-5">登録したコーヒー豆</h1>
      <hr class="style-1">
      <% if @beans.present? %>
        <%= render partial: "user-bean", collection: @beans, as: :bean %>
      <% else %>
        <h3 class="text-center steel-gray">まだ登録がありません</h3>
      <% end %>
    </div>
  </div>
</div>