config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "beans_comments#index"
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
  resources :users
  put "users/:id/hide", to: "users#hide", as: "users_hide"
  get "users/:id/profile", to: "users#show", as: "user_profile"
  resources :shops do
    resources :shop_comments
  end
  resources :beans do
    resources :beans_comments
  end
  resources :users, only: [:show, :edit]

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    get "users/sign_out" => "devise/sessions#destroy"
  end
end

app/controllers/beans_controller.rb
class BeansController < ApplicationController
  before_action :authenticate_user!, { except: [:index] }
  before_action :set_bean, { only: [:show, :edit, :update, :destroy] }
  before_action :set_bean_q, { only: [:index] }

  PER_PAGE = 9

  def index
    if params[:q].present?
      @beans = @q.result.page(params[:page]).includes(:shop).per(PER_PAGE)
      @count = @beans.total_count
    else
      params[:q] = { sorts: "created_at desc" }
      @beans = Bean.includes(:shop).order(:created_at).page(params[:page]).per(PER_PAGE)
    end
  end

  def new
    @bean = Bean.new
  end

  def create
    @bean = current_user.beans.new(bean_params)
    if @bean.save
      redirect_to beans_path, notice: "登録しました"
    else
      flash.now[:alert] = "登録に失敗しました"
      render :new
    end
  end

  def show
    @bean_comments = @bean.beans_comments.includes(:user)
    @bean_comment = current_user.beans_comments.new
  end

  def edit; end

  def update
    @bean.update!(bean_params)
    redirect_to @bean, notice: "コーヒー豆の情報を更新しました"
  end

  def destroy
    @bean.destroy!
    redirect_to(fallback_location: root_path, notice: "削除しました")
  end

  private

  def set_bean
    @bean = Bean.find(params[:id])
  end

  def bean_params
    params.require(:bean).permit(:name, :price, :country, :farm, :variety, :screen_size, :img, :user_id, :shop_id)
  end

  def set_bean_q
    @q = Bean.ransack(params[:q])
  end
end

app/helpers/beans_helper.rb
module BeansHelper
end

app/views/beans/_bean-comment.html.erb
<%= form_for [@bean, @bean_comment] do |f| %>
  <table class="table table-borderless">
    <tbody>
      <tr>
        <th scope="row">内容</th>
        <td colspan="2"><%= f.text_area :content %></td>
      </tr>
      <tr>
        <th scope="row">苦味</th>
        <td>
          <div class="form-group" id="bitterness">
            <%= f.label :bitterness, "苦味" %>
            <%= f.hidden_field :bitterness, id: :review_star %>
          </div>
          <script>
            $('#bitterness').empty();
              $('#bitterness').raty({
                size     : 36,
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn : '<%= asset_path('star-on.png') %>',
            
                scoreName: 'beans_comment[bitterness]',
                half: false,
              });
          </script>
        </td>
      </tr>
      <tr>
        <th scope="row">酸味</th>
        <td>
          <div class="form-group" id="acidity">
            <%= f.label :acidity, "酸味" %>
            <%= f.hidden_field :acidity, id: :review_star %>
          </div>
          <script>
            $('#acidity').empty();
              $('#acidity').raty({
                size     : 36,
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn : '<%= asset_path('star-on.png') %>',
            
                scoreName: 'beans_comment[acidity]',
                half: false,
              });
          </script>
        </td>
      </tr>
      <tr>
        <th scope="row">コク</th>
        <td>
          <div class="form-group" id="body">
            <%= f.label :body, "コク" %>
            <%= f.hidden_field :body, id: :review_star %>
          </div>
          <script>
            $('#body').empty();
              $('#body').raty({
                size     : 36,
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn : '<%= asset_path('star-on.png') %>',
            
                scoreName: 'beans_comment[body]',
                half: false,
              });
          </script>
        </td>
      </tr>
      <tr>
        <%= f.hidden_field :bean_id, value: @bean.id %>
        <td colspan="2">
          <div class="comment-button">
            <%= f.submit "コメントする", class: "btn  btn-block form-submit-btn" %>
          </div>
        </td>
      </tr>
    </tbody>
  </table>
<% end %>

app/views/beans/_bean-comments.erb
<div class="comments">
  <div class="row">
    <div class="col-2 registered-user">
      <a class="steel-gray" href="/users/<%= c.user.id %>"><img src=<%= c.user.img.url %> class="icon-image-mini">
        <p><%= c.user.name %></p>
      </a>
    </div>
    <div class="col-10 comment">
      <p><%= c.content %></p>
      <hr>
      <div class="rate-star">
        <div class="row">
          <div class="col-5 rate">
            <p>苦味</p>
          </div>
          <div class="col-7 star-rate">
            <div id="bitterness<%= c.id %>"></div>
            <script>
              $('#bitterness<%= c.id%>').empty();
                $('#bitterness<%= c.id%>').raty({
                  size      : 36,
                  starOff   : '<%= asset_path('star-off.png') %>',
                  starOn    : '<%= asset_path('star-on.png') %>',
                  half      : false,
                  readOnly: true,
                  score: <%= c.bitterness %>,
                });
            </script>
          </div>
        </div>
      </div>
      <div class="rate-star">
        <div class="row">
          <div class="col-5 rate">
            <p>酸味</p>
          </div>
          <div class="col-7 star-rate">
            <div id="acidity<%= c.id %>"></div>
            <script>
              $('#acidity<%= c.id%>').empty();
                $('#acidity<%= c.id%>').raty({
                  size      : 36,
                  starOff   : '<%= asset_path('star-off.png') %>',
                  starOn    : '<%= asset_path('star-on.png') %>',
                  half      : false,
                  readOnly: true,
                  score: <%= c.acidity %>,
                });
            </script>
          </div>
        </div>
      </div>
      <div class="rate-star">
        <div class="row">
          <div class="col-5 rate">
            <p>コク</p>
          </div>
          <div class="col-7 star-rate">
            <div id="body<%= c.id %>"></div>
            <script>
              $('#body<%= c.id%>').empty();
                $('#body<%= c.id%>').raty({
                  size      : 36,
                  starOff   : '<%= asset_path('star-off.png') %>',
                  starOn    : '<%= asset_path('star-on.png') %>',
                  half      : false,
                  readOnly: true,
                  score: <%= c.body %>,
                });
            </script>
          </div>
        </div>
      </div>
      <div class="row delete-link">
        <% if current_user && current_user.id == c.user_id %>
          <%= link_to "削除", bean_beans_comment_path(@bean, c), method: :delete, data: { confirm: "削除しますか？" } %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/beans/_bean-comments.html.erb
<%= @bean_comments.each do |c| %>
  <div class="comments">
    <div class="row">
      <div class="col-2 registered-user">
        <a class="steel-gray" href="/users/<%= c.user.id %>"><img src=<%= c.user.img.url %> class="icon-image-mini" alt="ユーザーイメージ">
          <p><%= c.user.name %></p>
        </a>
      </div>
      <div class="col-10 comment">
        <p><%= c.content %></p>
        <hr>
        <div class="rate-star">
          <div class="row">
            <div class="col-5 rate">
              <p>苦味</p>
            </div>
            <div class="col-7 star-rate">
              <div id="bitterness<%= c.id %>"></div>
              <script>
                $('#bitterness<%= c.id%>').empty();
                  $('#bitterness<%= c.id%>').raty({
                    size      : 36,
                    starOff   : '<%= asset_path('star-off.png') %>',
                    starOn    : '<%= asset_path('star-on.png') %>',
                    half      : false,
                    readOnly: true,
                    score: <%= c.bitterness %>,
                  });
              </script>
            </div>
          </div>
        </div>
        <div class="rate-star">
          <div class="row">
            <div class="col-5 rate">
              <p>酸味</p>
            </div>
            <div class="col-7 star-rate">
              <div id="acidity<%= c.id %>"></div>
              <script>
                $('#acidity<%= c.id%>').empty();
                  $('#acidity<%= c.id%>').raty({
                    size      : 36,
                    starOff   : '<%= asset_path('star-off.png') %>',
                    starOn    : '<%= asset_path('star-on.png') %>',
                    half      : false,
                    readOnly: true,
                    score: <%= c.acidity %>,
                  });
              </script>
            </div>
          </div>
        </div>
        <div class="rate-star">
          <div class="row">
            <div class="col-5 rate">
              <p>コク</p>
            </div>
            <div class="col-7 star-rate">
              <div id="body<%= c.id %>"></div>
              <script>
                $('#body<%= c.id%>').empty();
                  $('#body<%= c.id%>').raty({
                    size      : 36,
                    starOff   : '<%= asset_path('star-off.png') %>',
                    starOn    : '<%= asset_path('star-on.png') %>',
                    half      : false,
                    readOnly: true,
                    score: <%= c.body %>,
                  });
              </script>
            </div>
          </div>
        </div>
        <div class="row delete-link">
          <% if current_user && current_user.id == c.user_id %>
            <%= link_to "削除", bean_beans_comment_path(@bean, c), method: :dlete, data: { confirm: "削除しますか?" } %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/beans/_bean.html.erb
<div class="cards">
  <a href="/beans/<%= bean.id %>" class="cards-body">
    <div class="cards-header">
      <% if bean.img? %>
        <img src=<%= bean.img.url %>>
      <% else %>
        <%= image_tag "default-beans.jpg" %>
      <% end %>
    </div>
    <div class="bean-title">
      <P class="name"><%= bean.name %></P>
    </div>
  </a>
  <div class="contents steel-gray">
    <div class="underline">
      <p class="bean-tag">販売店</p>
      <p class="bean-content"><a href="/shops/<%= bean.shop_id %>"><%= bean.shop.name %></a></p>
    </div>
    <div class="underline">
      <p class="bean-tag">生産地</p>
      <p class="bean-content"><%= bean.country %></p>
    </div>
    <div class="underline">
      <p class="bean-tag">価格(100g)</p>
      <p class="bean-content"><%= bean.price %>円</p>
    </div>
  </div>
  <p class="link-box">
    <% if user_signed_in? && current_user.id == bean.user_id %>
      <%= link_to "編集", edit_bean_path(bean) %>
      <%= link_to "削除", bean_path(bean), method: :delete, data: { confirm: "削除しますか？" } %>
    <% end %>
  </p>
</div>

app/views/beans/_bean_form.html.erb
  
<div class="form-wrapper">
  <%= form_with model: @bean, local: true do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <div class=form-group>
      <span class="essential">※</span><%= f.label :shop_id, "販売店名" %>
      <%= f.select :shop_id, Shop.all.map { |p| [p.name, p.id] }, {prompt: "---"}, {class: "form-control", style: "margin-bottom: 15px;", data: {} } %>
    </div>
    <div class=form-group>
      <span class="essential">※</span><%= f.label :name, "豆の名前" %>
      <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: "最大50文字", maxlength: 50 %>
    </div>
    <div class=form-group>
      <span class="essential">※</span><%= f.label :price, "価格" %>
      <%= f.number_field :price, autofocus: true, class: "form-control", placeholder: "100g当たりの価格" %>
    </div>
    <div class=form-group>
      <span class="essential">※</span><%= f.label :country, "生産地" %>
      <%= f.select :country, Bean.countries.keys.map {|k| [k, k]}, {}, {class: "form-control", style: "margin-bottom: 15px;", data: {} } %>
    </div>
    <div class=form-group>
      <%= f.label :farm, "農園" %>
      <%= f.text_field :farm, autofocus: true, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :variety, "品種" %>
      <%= f.text_field :variety, autofocus: true, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :screen_size, "大きさ" %>
      <%= f.number_field :screen_size, autofocus: true, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :img, "豆のイメージ" %><br />
      <%= f.file_field :img %>
    </div>
    <div class="search-button">
      <%= f.submit "登録", class: "btn btn-block form-submit-btn" %>
    </div>
  <% end %>
</div>

app/views/beans/_comment.html.erb
<%= form_with(model: [@bean, @bean_comment]) do |f| %>
  <table class="table table-borderless">
    <tbody>
      <tr>
        <th scope="row">内容</th>
        <td><%= f.text_area :content %></td>
      </tr>
      <tr>
        <th scope="row">苦味</th>
        <td>
          <div class="form-group" id="bitterness">
            <%= f.label :bitterness, "苦味" %>
            <%= f.hidden_field :bitterness, id: :review_star %>
          </div>
          <script>
            $('#bitterness').empty();
              $('#bitterness').raty({
                size     : 36,
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn : '<%= asset_path('star-on.png') %>',
            
                scoreName: 'beans_comment[bitterness]',
                half: false,
              });
          </script>
        </td>
      </tr>
      <tr>
        <th scope="row">酸味</th>
        <td>
          <div class="form-group" id="acidity">
            <%= f.label :acidity, "酸味" %>
            <%= f.hidden_field :acidity, id: :review_star %>
          </div>
          <script>
            $('#acidity').empty();
              $('#acidity').raty({
                size     : 36,
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn : '<%= asset_path('star-on.png') %>',
            
                scoreName: 'beans_comment[acidity]',
                half: false,
              });
          </script>
        </td>
      </tr>
      <tr>
        <th scope="row">コク</th>
        <td>
          <div class="form-group" id="body">
            <%= f.label :body, "コク" %>
            <%= f.hidden_field :body, id: :review_star %>
          </div>
          <script>
            $('#body').empty();
              $('#body').raty({
                size     : 36,
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn : '<%= asset_path('star-on.png') %>',
            
                scoreName: 'beans_comment[body]',
                half: false,
              });
          </script>
        </td>
      </tr>
      <tr>
        <%= f.hidden_field :bean_id, value: @bean.id %>
        <td colspan="2">
          <div class="comment-button">
            <%= f.submit "コメントする", class: "btn  btn-block form-submit-btn" %>
          </div>
        </td>
      </tr>
    </tbody>
  </table>
<% end %>

app/views/beans/edit.html.erb
<div class="container">
  <h1 class="title mt-3">豆を編集</h1>
  <%= render "bean_form" %>
</div>

app/views/beans/index.html.erb
<div class=row>
  <div class="col-xl-3 search-form">
    <div class="form-wrapper">
      <h1 class="title">Search</h1>
      <%= search_form_for @q, url: beans_path do |f| %>
        <div class="form-group">
          <%= f.label "並べ替え", {class: "search-tag"} %>
          <%= f.select( :sorts, {"新着順": "created_at desc", "価格が安い順": "price asc", "価格が高い順": "price desc"}, { selected: params[:q][:sorts] }, class: "form-control") %>
        </div>
        <div class=form-group>
          <%= f.label :shop_name_cont, "販売店名", {class: "search-tag"} %>
          <%= f.search_field :shop_name_cont, autofocus: true, class: "form-control" %>
        </div>
        <div class=form-group>
          <%= f.label :name_cont, "コーヒー豆名", {class: "search-tag"} %>
          <%= f.search_field :name_cont, autofocus: true, class: "form-control" %>
        </div>
        <div class=form-group>
          <%= f.label :country_eq, "生産地", {class: "search-tag"} %>
          <%= f.select :country_eq, Bean.countries_i18n.invert.map { |key, value| [key, Bean.countries[value]]}, {include_blank: "指定なし"}, { class: "form-control", style: "margin-bottom: 15px;", data: {} } %>
        </div>
        <div class=form-group>
          <%= f.label :farm_cont, "生産農園", {class: "search-tag"} %>
          <%= f.search_field :farm_cont, autofocus: true, class: "form-control" %>
        </div>
        <div class=form-group>
          <%= f.label :variety_cont, "品種", {class: "search-tag"} %>
          <%= f.search_field :variety_cont, autofocus: true, class: "form-control" %>
        </div>
        <div class=form-group>
          <%= f.label :price, "価格(100g当たり)", {class: "search-tag"} %>
          <%= f.number_field :price_gteq, class: "form-control", placeholder: "¥ Min" %>
          <p class="price">〜</p>
          <%= f.number_field :price_lteq, class: "form-control", placeholder: "¥ Max" %>
        </div>
        <div class="search-button">
          <%= f.submit "検索", class: "btn btn-block form-submit-btn" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-xl-9">
    <h1 class="title">Beans</h1>
    <h4 class="title text-center mb-5"><%= @count %>件の検索結果</h4>
    <div class="wrap">
      <%= render @beans %>
    </div>
  </div>
</div>
<%= paginate @beans %>

app/views/beans/new.html.erb
<div class="container">
  <h1 class="title mt-3">豆を登録</h1>
  <%= render "bean_form" %>
</div>

app/views/beans/show.html.erb
<h1 class="title mt-3"><%= @bean.name %></h1>
<div class="shop-show">
  <div class="row">
    <%= render partial: "layouts/object-img", locals: { object: @bean, img: "beans" } %>
    <div class="col-xl-8 shop-detail">
      <div class="row">
        <div class="col-lg-6 shop-about">
          <h2 class="title show">About</h2>
          <table class="table table-borderless">
            <tbody>
              <tr>
                <th scope="row">苦味レベル</th>
                <td>
                  <div class="average-review-rating" data-score=<%= @bean_comments.average(:bitterness) %>></div>
                  <%= render "/layouts/average" %>
                </td>
              </tr>
              <tr>
                <th scope="row">酸味レベル</th>
                <td>
                  <div class="average-review-rating" data-score=<%= @bean_comments.average(:acidity) %>></div>
                  <%= render "/layouts/average"  %>
                </td>
              </tr>
              <tr>
                <th scope="row">コクレベル</th>
                <td>
                  <div class="average-review-rating" data-score=<%= @bean_comments.average(:body) %>></div>
                  <%= render "/layouts/average"  %>
                </td>
              </tr>
              <tr>
                <th scope="row">販売店名</th>
                <td>
                  <a class="steel-gray" href="/shops/<%= @bean.shop.id %>"><%= @bean.shop.name %></a>
                </td>
              </tr>
              <tr>
                <th scope="row">価格(100g)</th>
                <td colspan="2"><%= @bean.price %><span>円</span></td>
              </tr>
              <tr>
                <th scope="row">産地</th>
                <td colspan="2"><%= @bean.country %></td>
              </tr>
              <% if @bean.farm.present? %>
                <tr>
                  <th scope="row">農園</th>
                  <td><%= @bean.farm %></td>
                </tr>
              <% end %>
              <% if @bean.variety.present? %>
                <tr>
                  <th scope="row">品種</th>
                  <td><%= @bean.variety %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="col-lg-6 shop-comments">
          <h2 class="title show">Comments</h2>
          <%= render partial: "bean-comments", collection: @bean_comments, as: :c %>
          <div class="comments">
            <%= render "comment" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>