config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "beans_comments#index"
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
  resources :users
  put "users/:id/hide", to: "users#hide", as: "users_hide"
  get "users/:id/profile", to: "users#show", as: "user_profile"
  resources :shops do
    resources :shop_comments
  end
  resources :beans do
    resources :beans_comments
  end
  resources :users, only: [:show, :edit]

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
    get "users/sign_out" => "devise/sessions#destroy"
  end
end

app/views/layouts/_average.html.erb
<script>
  $('.average-review-rating').empty();
    $('.average-review-rating').raty({
      readOnly: true,
      starOn: "<%= asset_path('star-on.png') %>",
      starOff: "<%= asset_path('star-off.png') %>",
      starHalf: "<%= asset_path('star-half.png') %>",
      score: function() {
        return $(this).attr('data-score')
      }
    });
</script>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, msg| %>
  <div class="alert alert-<%= flash_type %>" role="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="nav navbar-expand-md navbar-dark fixed-top" id="mainNav">
  <div class="navbar-brand">
    <% if user_signed_in? %>
      <h1 class="text-4xl font-semibold md:text-xl"><%= link_to "Coffee First", beans_path, class: "btn btn-lg"  %></h1>
    <% else %>
      <h1 class="text-4xl font-semibold md:text-xl"><%= link_to "Coffee First", root_path, class: "btn btn-lg"  %></h1>
    <% end %>
  </div>
  <button class="navbar-toggler hamburger-menu" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item dropdown active mr-3">
        <a class="nav-link float-left" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          検索
        </a>
        <div class="dropdown-menu" aria-labelladby="navbarDropdownMenuLink">
          <%= link_to "お店を検索", shops_path, class: "dropdown-item" %>
          <%= link_to "豆を検索", beans_path, class: "dropdown-item" %>
        </div>
      </li>
      <li class="nav-item dropdown active mr-3">
        <a class="nav-link float-left" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          登録
        </a>
        <div class="dropdown-menu" aria-labelladby="navbarDropdownMenuLink">
          <%= link_to "お店を登録", new_shop_path, class: "dropdown-item" %>
          <%= link_to "豆を登録", new_bean_path, class: "dropdown-item" %>
        </div>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item dropdown active mr-3">
          <a class="nav-link float-left" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.name %>
          </a>
          <div class="dropdown-menu" aria-labelladby="navbarDropdownMenuLink">
            <%= link_to "アカウント詳細", user_path(current_user), class: "dropdown-item" %>
            <% if current_user.email != "guest@example.com" %>
              <%= link_to "アカウント編集", edit_user_registration_path, class: "dropdown-item" %>
            <% end %>
          </div>
        </li>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "ログアウトしますか？"}, class: "nav-item nav-link active text-left" %>
      <% else %>
        <%= link_to "新規登録", new_user_registration_path, class: "nav-item nav-link active text-left mr-3" %>
        <%= link_to "ログイン", new_user_session_path, class: "nav-item nav-link active text-left mr-3" %>
        <%= link_to "ゲストログイン（閲覧用）", users_guest_sign_in_path, method: :post, class: "nav-item nav-link active text-left" %>
      <% end %>
    </ul>
  </div>
</nav>
<% if current_page?(root_path) %>
  <header class="masthead">
    <div class="container">
      <div class="masthead-subheading">あなたのお気に入りの一杯をみつけよう</div>
      <div class="masthead-heading">Coffee First</div>
      <%= link_to "新規登録", new_user_registration_path, class: "btn btn-orange btn-xl"%>
      <%= link_to "ログイン", new_user_session_path, class: "btn btn-salmon btn-xl" %>
      <%= link_to "ゲストログイン（閲覧用）", users_guest_sign_in_path, method: :post, class: "btn btn-spearmint btn-xl" %>    </div>
  </header>
<% end %>

app/views/layouts/_object-img.html.erb
<div class="col-xl-4 shop-picture">
  <% if object.img? %>
    <img src=<%= object.img.url %> class="img-fluid">
  <% else %>
    <%= image_tag "default-#{img}.jpg", class: "img-fluid" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoffeeFirst</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <main>
      <%= render "layouts/flash" %>
      <div class="base-container">
        <%= yield %>
      </div>
    </main>
    <footer>
      <p>© Kohei Hashimoto All rights reserved</p>
    </footer>
  </body>
</html>